# Site settings
title: Moshe Wasserblat blog
email: 
description: "Efficient and Robust NLP"
baseurl: ""
url: "http://MosheWasserb.github.io"
twitter_username: MosheWasserblat
github_username:  MosheWasserb

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
