# Site settings
title: Moshe Wasserblat blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://MosheWasserb.github.io"
twitter_username: moshe
github_username:  MosheWasserb

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
